import CommonConstantsInfo from '../../viewmodel/CommonConstantsInfo';

export class CommonConstants {
  // width & height
  static readonly FULL_WIDTH: string = '100%';
  static readonly FULL_HEIGHT: string = '100%';
  // fontWeight
  static readonly FONT_WEIGHT_400: number = 400;
  static readonly FONT_WEIGHT_500: number = 500;
  static readonly FONT_WEIGHT_700: number = 700;
  static readonly FONT_WEIGHT_900: number = 900;
  // letter spacing
  static readonly LETTER_1: number = 0.1;
  static readonly LETTER_34: number = 3.4;
  // opacity
  static readonly OPACITY_4: number = 0.4;
  static readonly OPACITY_6: number = 0.6;
  // offset
  static readonly ZERO: number = 0;
  static readonly MINUS_20: number = -20;
  static readonly HAS_NO_INDEX: number = -1;
  static readonly OFFSET_24: number = -24;
  // duration
  static readonly AD_DURATION: number = 5; // 5s
  static readonly LAUNCHER_DELAY_TIME: number = 2000; // 2000ms
  static readonly DURATION_1000: number = 1000; // 1000ms
  static readonly DURATION_800: number = 800; // 700ms
  static readonly DURATION_100: number = 100; // 100ms
  // list space
  static readonly SPACE_4: number = 4;
}